# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='users_who_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_from_user', to='qapp.Users'),
        ),
        migrations.AddField(
            model_name='likes',
            name='quotes_with_likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedquotes', to='qapp.Quotes'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_who_likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedbyuser', to='qapp.Users'),
        ),
    ]
