# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp', '0002_remove_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
